// <auto-generated />

namespace Sharlayan.Resources {
    using System.Collections.Generic;

    using Signature = Sharlayan.Models.Signature;
    using ChatLogPointersStructure = Sharlayan.Models.Structures.ChatLogPointers;
    using StructuresContainer = Sharlayan.Models.Structures.StructuresContainer;

    internal static class GeneratedChatResources {
        internal const string FcsCommit = "15ae1806b0c175d1e2dd2ae845e4c853f332fd07";

        internal static Signature[] CreateSignatures() {
            return new[] {
                new Signature {
                    ASMSignature = true,
                    Key = global::Sharlayan.Signatures.CHATLOG_KEY,
                    PointerPath = new List<long> { -7, 0, 0x2B68, 0x1AC0 },
                    Value = "488B1D????????8B7C24",
                },
            };
        }

        internal static StructuresContainer CreateStructures() {
            return new StructuresContainer {
                ChatLogPointers = new ChatLogPointersStructure {
                    OffsetArrayStart = 0x48,
                    OffsetArrayPos = 0x50,
                    OffsetArrayEnd = 0x58,
                    LogStart = 0x60,
                    LogNext = 0x68,
                    LogEnd = 0x70,
                },
            };
        }
    }
}
